" PLUGINS {{{

" TODO Auto installation of 'vim-plug' for Neovim by 'Windows (PowerShell)'.
call plug#begin('~/AppData/Local/nvim/plugged')
" Fake text.
Plug 'tkhren/vim-fake'
" Dracula theme.
Plug 'dracula/vim', { 'as': 'dracula' }
call plug#end()

colorscheme dracula

" }}}

" BASICS {{{

" Sessions.
set sessionoptions+=globals

" Faster redrawing.
set lazyredraw
set ttyfast
set updatetime=2000
set ttimeoutlen=0

" For integration with Russian layout.
set langmap=ёйцукенгшщзхъфывапролджэячсмитьбюЁЙЦУКЕHГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ;`qwertyuiop[]asdfghjkl\\;'zxcvbnm\\,.~QWERTYUIOP{}ASDFGHJKL:\\"ZXCVBNM<>

" Show full count of search matches.
set shortmess-=S

" For integration with system buffer.
set clipboard+=unnamedplus

" Command line executor.
set shell=zsh

" Disable compatibility with 'vi' which can cause unexpected issues.
set nocompatible

" Сertain directories for backups, swaps and undos.
set backupdir=~/.vim/backup
set directory=~/.vim/swap
set noundofile

" Graphic and sound effects.
set novisualbell " Don't blink.
set t_vb= " No flicker.
set visualbell t_vb= " Disable sound.

" Line numbering.
set number
set relativenumber
set ruler " Information about the current row, column, etc.

set termguicolors

" Syntax and files.
syntax on
filetype plugin indent on
set encoding=utf8
set fileencodings=utf8
set ff=unix

" Spell check.
" Useful commands: `]s`, `[s`, `zg`, `z=`.
set nospell " Disabled by default in order to switch later via shortcuts.
set spelllang=en_us,ru_ru
" Usage: move the cursor to the wrong word and press 'z='

" Tabulation.
set autoindent " Copies indents from the current line when adding a new one.
set smartindent " The same as autoindent, but in addition, automatically sets
" indents in the right places.
set tabstop=2 " The number of spaces with which the tab character is displayed
" in the text.
set shiftwidth=2 " To adjust the width of the indents in the spaces added by
" '>>' and '<<' commands.
set softtabstop=2 " The number of spaces that a tab character displays when
" appending.
set expandtab
set smarttab

" Mouse.
if has('mouse')
  set mouse=a
endif
set mousehide " Hide mouse cursor while typing.

" TODO WTF???
" if !has('nvim')
"   set ttymouse=xterm-256color " For integration with Alacritty terminal.
" endif

" Vertical bar.
set textwidth=80
set colorcolumn=80
hi ColorColumn ctermbg=red

" Highlight cursor line underneath the cursor horizontally.
set cursorline
" Do not let cursor scroll below or above N number of lines/columns when
" scrolling.
set scrolloff=5
set sidescrolloff=5
" Show partial command you type in the last line of the screen.
set showcmd
" Show the current mode.
set showmode
" Clear status line when config is reloaded.
set statusline=''
set completeopt=menu,menuone,noselect

" Search.
set hlsearch
set incsearch
set showmatch " Show matching words during a search.
set gdefault " Add the 'g' flag to search/replace by default.
set ignorecase
set wildignorecase
set smartcase " If the search pattern contains upper case characters, it will
" search in a case sensitive manner.

set history=1000

" TODO https://www.reddit.com/r/neovim/comments/3v06lo/making_the_background_transparent/
au ColorScheme * hi Normal ctermbg=none guibg=none
au ColorScheme myspecialcolors hi Normal ctermbg=red guibg=red

" Netrw file explorer settings.
let g:netrw_banner = 0 " Hide banner above files.
let g:netrw_liststyle = 3 " Tree instead of plain view.
let g:netrw_browse_split = 3 " Vertical split window when <CR> pressed on file.

" }}}

" MAPPINGS {{{

" TODO Make functions for key bindings.

" All modes.
" Disables.
noremap <PageUp> <nop>
noremap! <PageUp> <nop>
noremap <PageDown> <nop>
noremap! <PageDown> <nop>
noremap <Home> <nop>
noremap! <Home> <nop>
noremap <End> <nop>
noremap! <End> <nop>

" Normal mode.
" Stay in indent mode.
nnoremap <silent> > >>
nnoremap <silent> <Tab> >>
nnoremap <silent> < <<
nnoremap <silent> <S-Tab> <<
" Better window navigation (soon).
" nnoremap <silent> <C-h> <C-w>h
" nnoremap <silent> <C-j> <C-w>j
" nnoremap <silent> <C-k> <C-w>k
" nnoremap <silent> <C-l> <C-w>l
" Space as usual.
nnoremap <Space> a<Space><Esc>
" Additional functionality for `<Esc>`: clear last search highlighting.
nmap <Esc> <Esc>:nohl<CR>
" Adding line breaks directly from Normal mode.
nnoremap <CR> o<Esc>
" FIXME
nnoremap <S-CR> O<Esc>
" Toggle case without moving cursor.
nnoremap t g~l
" I think it's a better solution.
nnoremap <S-u> <C-r>
" Go Edit (word).
nnoremap ge "_ciw

" Insert mode.
" Additional functionality for `<Esc>`: clear last search highlighting.
imap <Esc> <Esc>:nohl<CR>
" For snippet lookup.
inoremap <Space><Space> <Esc>/<++><CR>"_c4l

" Visual mode.
" Stay in indent mode.
vnoremap <silent> > >gv
vnoremap <silent> <Tab> >gv
vnoremap <silent> < <gv
vnoremap <silent> <S-Tab> <gv
" Additional functionality for `<Esc>`: clear last search highlighting.
vmap <Esc> <Esc>:nohl<CR>
" Fast surroundings.
vmap ' S'
vmap " S"
vmap ` S`
vmap ( S(
vmap ) S)
vmap _ S_

" }}}

" MY SNIPPETS {{{

" FIXME Remove after configuration 'L3MON4D3/LuaSnip'.
" NOTE Don't use Vim snippets in file (like this one), that contains `<++>`.

" All.
autocmd FileType * imap <silent> ,db DEBUG<Esc>\\
autocmd FileType * imap <silent> ,nt NOTE<Esc>\\
autocmd FileType * imap <silent> ,in INFO<Esc>\\
autocmd FileType * imap <silent> ,fx FIXME<Esc>\\

" Vim.
" Block comment.
autocmd FileType vim imap <silent> ,bc " <++> {{{<CR><Esc>cc<CR><++><CR><Space><Space>
autocmd FileType vim imap <silent> ,cb ,bc
" Echo debug.
autocmd FileType vim imap <silent> ,ed echomsg <++> \| " DEBUG<Space><Space>
autocmd FileType vim imap <silent> ,de ,ed
" Function.
autocmd FileType vim imap <silent> ,f function! s:<++>(<++>) abort<CR><++><Esc>kf<i<Space><Space>

" Markdown.
" En-Dash.
autocmd FileType markdown imap <silent> ,nd &ndash;
autocmd FileType markdown imap <silent> ,dn ,nd
" Link.
autocmd FileType markdown imap <silent> ,l [<++><Esc>la(<++><Space><Space>
" Link with Title.
autocmd FileType markdown imap <silent> ,lt [<++><Esc>la(<++> "<++><Space><Space>
autocmd FileType markdown imap <silent> ,tl ,lt
" Italic.
autocmd FileType markdown imap <silent> ,i *<++>*<++><Space><Space>
" Bold.
autocmd FileType markdown imap <silent> ,b **<++>**<++><Space><Space>
" Bold and italic.
autocmd FileType markdown imap <silent> ,e ***<++>***<++><Space><Space>
" Blockquotes.
autocmd FileType markdown imap <silent> ,q > <++><Space><Space>
" Ordered List.
autocmd FileType markdown imap <silent> ,ol 1. <++><CR>2. <++><Space><Space>
" Unordered List.
autocmd FileType markdown imap <silent> ,ul - <++><CR>- <++><Space><Space>
" Code Block.
autocmd FileType markdown imap <silent> ,cb ```<++><CR><++><Space><Space>
" Image.
autocmd FileType markdown imap <silent> ,im ![<++><Esc>la(<++> "<++><Space><Space>

" }}}
