[general]
import = ["C:/Users/dmitr/AppData/Roaming/alacritty/atom_one_light.toml"]
# import = ["C:/Users/dmitr/AppData/Roaming/alacritty/dracula.toml"]
# import = ["C:/Users/dmitr/AppData/Roaming/alacritty/gruvbox_dark.toml"]
# import = ["C:/Users/dmitr/AppData/Roaming/alacritty/gruvbox_light.toml"]
# import = ["C:/Users/dmitr/AppData/Roaming/alacritty/one_dark.toml"]
# import = ["C:/Users/dmitr/AppData/Roaming/alacritty/solarized_dark.toml"]
# import = ["C:/Users/dmitr/AppData/Roaming/alacritty/solarized_light.toml"]
# import = ["C:/Users/dmitr/AppData/Roaming/alacritty/tokyo-night-storm.toml"]
# import = ["C:/Users/dmitr/AppData/Roaming/alacritty/tokyo-night.toml"]

live_config_reload = true
working_directory = "C:/Users/dmitr"

[colors]
draw_bold_text_with_bright_colors = true

[debug]
log_level = "Off"

[font]
size = 11.0

[font.bold]
family = "Hack NF"
style = "Bold"

[font.bold_italic]
family = "Hack NF"
style = "Bold Italic"

[font.italic]
family = "Hack NF"
style = "Italic"

[font.normal]
family = "Hack NF"
style = "Regular"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["--login", "-i"]
program = "C:/Program Files/Git/bin/bash.exe"

[scrolling]
history = 1000
multiplier = 5

[window]
opacity = 0.97
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5
